name: "EOeS"
description: "Epischer Ölzähler Service developed by Zuckerfressendes Stück Scheiße und Bigbrain Jöl"
version: "1.1"
slug: "eoes_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  5000/tcp: 5000
